version: 2.1
orbs:
  node: circleci/node@4.5.0

commands:
  setup-node-and-yarn-install-with-cache:
    steps:
      - node/install:
          install-yarn: true
          node-version: latest
      - node/install-packages:
          pkg-manager: yarn

jobs:
  lint-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - setup-node-and-yarn-install-with-cache
      - run:
          name: Lint
          command: yarn lint

workflows:
  node-tests:
    jobs:
      - lint-and-test
